version: '3.8'
services:
  app:
    image: station-ski  # Nom de l'image Docker de votre application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"  # Port correspond à celui défini dans application.properties
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""  # Si vous n'avez pas de mot de passe
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Utilisez un mot de passe sécurisé en production
      MYSQL_DATABASE: stationSki  # Nom de la base de données
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
